### ISSUE TITLE
Handling comments is not working as expected 

### ISSUE THREAD

**Issue by bharatl** [EDS-APHP/HiveQLKernel#12]
```
--databases
show databases
```

Failing with:
> only 'select', 'with', 'set property=value', 'create table x.y stored as orc' 'drop table', 'use database', 'show databases', 'show tables', 'describe myTable' statements are allowed

**Comment by bharatl** [comment]
the bug is at https://github.com/EDS-APHP/HiveQLKernel/blob/master/hiveql/kernel.py#L140

1) after splitting the input sql which has comments with '\n', we are joining with space and losing '\n'. 

2) sql_remove_comment  method matches/substitutes only if '\n' is present in the code.

**Comment by parisni** [comment]
thanks for the explanation and the fix !
