### ISSUE TITLE
Add timing for queries

### ISSUE THREAD

**Issue by parisni** [EDS-APHP/HiveQLKernel#20]
would be great to track query timing in the notebook

**Comment by Dubrzr** [comment]
Is this related to #1  and #10 ?

**Comment by parisni** [comment]
Not really, just to get the final time processing of the query in the result, above the table.

> query time: 2 min 4 seconds

**Comment by parisni** [comment]
Something like:
> table dropped ! (query time: 2ms)
> table created ! (query time: 2 min 4 seconds)
