### ISSUE TITLE
Allow multiple queries for SET <key>=<value> commands in a cell

### ISSUE THREAD

**Issue by bharatl** [EDS-APHP/HiveQLKernel#22]
@parisni @Dubrzr 

It would be good if we allow multiple SET commands  in a cell. 
use case:  If a user has to set many variables, user will end up writing each SET in a different cell 

Solution: 
a) Code cell should only have SET commands with semicolon terminated
example <br />SET hive.abc=def; \
  SET hive.zyz=ijk; 

b) Throw MultipleQueriesError when the code cell contains code other than SET

c) Split the cell code by semicolon(;), check if it starts with SET then send the command to kernel  in a loop 

Let me know your thoughts as this may be helpful for users

**Comment by parisni** [comment]
This makes sense. Also we should allow both USE and SET

**Comment by bharatl** [comment]
@parisni @Dubrzr  raised [PR](https://github.com/EDS-APHP/HiveQLKernel/pull/23/files) 

We are now supporting:

_SET key=value_ `(sets variables)`<br />  
_SET_ `prints all the available variables` <br /> 
_SET key_ `prints the key data` <br />

Regarding USE, could you please elaborate as of now USE <database> works perfectly fine

**Comment by Dubrzr** [comment]
Hi @bharatl ! Thanks for your contribution!

I think what Nicolas was talking about is to be able to write this:

```
USE some_database;
SHOW TABLES;
```

which is simply specifying a USE statement with another query.

Actually, we could classify commands like this:

1. Those who return data (displayed in a html table): SELECT, SHOW, ...
2. Those who don't return data: USE, SET...

And use this classification to let users specify multiple commands that don't return data with a single command that returns data.

**Comment by parisni** [comment]
@Dubrzr  agreed
That might imply some code refactoring.

**Comment by bharatl** [comment]
@parisni @Dubrzr If I understand correctly 

**1.** In a cell there could be multiple statements (semicolon terminated) which doesn't return anything (use, describe etc) and only one statement which returns data (select, show). 
**Action**: We have to support this  

**2.** In a cell if there are multiple statements (;) which returns data.
**Action**: we have to throw some error (multiple queries error)

Let me know the if my understanding is correct and feel free to add any other cases. I can come up with the code changes once we finalize

**Comment by Dubrzr** [comment]
I feel like you understood correctly :) I don't see other cases right now.

Ok awesome @bharatl!!!
Thanks a lot!

**Comment by bharatl** [comment]
@parisni @Dubrzr 

There is a simple solution:

After splitting the queries with semicolon, all the queries will go through self.last_conn.execute() method in a loop and returns SqlAlchemy ResultProxy Object. This Object will be NONE if it doesn't contains any rows, for example USE, CREATE, DROP etc commands will have ResultProxy as NONE and SELECT, SHOW etc commands will contain data in ResultProxy object 

If we have data to display, we can retrieve the data from ResultProxy object (ResultProxy.fetchall()) and  construct pandas dataframe using this ResultProxy.fetchall() method like below 

```
ResultSet = ResultProxy.fetchall() 
df = pd.Dataframe(ResultSet, colums=ResultSet.keys())
return df.fillna('NULL').astype(str).to_html(notebook=True)
```

If we doesn't have data (ResultProxy is NONE) to render then proceed to next command.

The above solution gets rid of all the restrictions we have currently and allow multiple selects in a cell 

Let me know your thoughts

**Comment by Dubrzr** [comment]
Does it still work with returning messages with commands such as USE?

For example, when someone use a USE statement, we want to send a message displayed like "Successfully changed to xxx databse!"

**Comment by bharatl** [comment]
@Dubrzr 

> Does it still work with returning messages with commands such as USE?
> 
> For example, when someone use a USE statement, we want to send a message displayed like "Successfully changed to xxx databse!"

No it wont display message  but on success execution_count will be incremented.

This behaviour would be similar to import statements in python `(ex: import pandas as pd)` won't send any message but execution count is incremented.

**Comment by bharatl** [comment]
@parisni @Dubrzr 

Raised [PR](https://github.com/EDS-APHP/HiveQLKernel/pull/24)

I have made changes to send the messages requested by @Dubrzr 

Also this PR addresses the [Better handle error message #8](https://github.com/EDS-APHP/HiveQLKernel/issues/8) 

Let me know if I need to do any other changes after your review comments

**Comment by parisni** [comment]
Hi @bharatl please take a look at the multiple_queries branch I did 2 days ago.
The idea is quite similar and I wonder what's the best solution:

1. use the proxy and concatenate the dataframe (as you propose)
2. concatenate the html in the result

Not sure about the behavior of 1. What happens when the dataframes  from 2 select queries are differents ?

The solution 2 also shows up the results of each steps as @Dubrzr was talking about and is also more flexible isn'it ?

**Comment by bharatl** [comment]
@parisni 

Regarding  _use the proxy and concatenate the dataframe (as you propose)_:

In my solution each time a select query is executed, dataframe(df) will be populated with the new data and that is sent back as shown below (I am not concatenating the dataframe)

```
result = self.last_conn.execute(query.strip())
if result is not None and result.returns_rows is True:
                    df = pd.DataFrame(result.fetchall(), columns=result.keys())
                    html = df_to_html(df)
```
So multiple select queries are handled well

I am also handling the results of each steps as @Dubrzr mentioned.

**Comment by Dubrzr** [comment]
So everytime the dataframe is filled with the latest select query? This would replace the MultipleQueriesError if I understand correctly?
Why not

**Comment by bharatl** [comment]
@Dubrzr thanks, let me know your comments

**Comment by Dubrzr** [comment]
@bharatl : merged! Available on pypi @ 1.0.13

@parisni : can you check we don't loose any feature?

Thanks,

**Comment by parisni** [comment]
Thanks @bharatl  ! 

I will add some tests to ensure no regression in the future @Dubrzr

**Comment by bharatl** [comment]
@Dubrzr @parisni Thank you
